# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"do_something": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://deutschmn.github.io/hi_nbdev/"

git_url = "https://github.com/deutschmn/hi_nbdev/tree/master/"

def custom_doc_links(name): return None
